<a href="https://colab.research.google.com/github/Raviteja199821/Ravi-Teja/blob/main/Pythonseries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world ")

hello world 


In [ ]:
print('hello world')

hello world


In [ ]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [ ]:
print("Total no of keywords", len(keyword.kwlist))

Total no of keywords 35


In [ ]:
True = 1
print(True)

SyntaxError: cannot assign to True (1179485487.py, line 1)

Identifiers

Identifiers is the name given to entities like class, functions, variables etc. in python.it helps differentiating one entity from another.

Rules for writing identifiers:
1.Identifiers can be a combination of letter in lowercase(a to z)or uppercase (A to Z)or digits (0 to 9) or an underscore(_).

2.An identifier cannot start with a digit. 1variable is invalid, but variable 1 is perfectly fine.
3.Keywords cannot be used as identifiers.


In [ ]:
pass1 = 1

In [ ]:
a_b_21 =10

Python Indentation
1. In programming language such as c, c++ and java use braces{} to show a group of code. However in python ,indentation is uesd instead.

2. A section of code,like in a function or loop,begins with an indented line and stops with the first line that in not indented.

3. you get to choose how much to indent, but it has to be the same for the whole section.

4. usually,four spaces are used for indentation in python, and it's better than using tabs.

In [ ]:
for i in range(10):
   print(i)

0
1
2
3
4
5
6
7
8
9


1. Indentation can be ignored in line continuation. But it's a good idea to always indent.

2. It makes the code more readable.

3. Follow industry standards.


In [ ]:
if True:
  print("Learning Python Easily")
  a = "Data Pyramid"
  print(a)

Learning Python Easily
Data Pyramid


In [ ]:
if True: print("Learning Python Easily"); a = "Data Pyramid"; print(a)

Learning Python Easily
Data Pyramid


But we don't use above method as this is not a standard.it's always recommended to use industry standard coding.

Multi Line Statement
In Python, end of a statement is marked by a newline character. But we can make a statement extend over multiple lines with the line continuation character().

In [ ]:
ravi = 1 + 2 +3 +4
print(ravi)

10


In [ ]:
ravi = 1 + 2 +3 +4\
       + 5 +10
print(ravi)

25


In [ ]:
#variable
a = 20
print(a)

20


In [ ]:
a,b,c = 10,"AAI", 5.5
print(a,b,c)


10 AAI 5.5


In [ ]:
#Storage locations
a = 3
print(id(a))

11277992


In [ ]:
x = 5
print(id(x))

11278056


Data types
1. Text data types => Strings
2. Numeric data types => Integer, float , complex
3. sequence data types => lists, tuples, range
4. Mapping data types => dictionaries.
5. set data types => sets
6. Boolean data types => true, False
7. binary data types => 0,1
8. None data type =>None

Data Structures:
They are of two types of data structures
1. Inbuild Data Structure
2. User Defined Data Structure

1.1) In In build data structures we have
1. lists => []
2. Tupleas => ()
3. Dictonary => {}
4. Sets => ()

2.1) In user defined data structures
we have
1. Stacks
2. queues
3. linked lists
4. trees
5. Graphs

In [ ]:
import keyword
print(keyword.kwlist)
print("Total no of keywords" , len(keyword.kwlist))

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
Total no of keywords 35


In [ ]:
False1 = 1
print(False)

False


In [ ]:
True@ = 1

SyntaxError: invalid syntax (323410020.py, line 1)

In [ ]:
a_b_1 = 10

In [ ]:
# a_10 = 10

In [ ]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
age = 28
print("I am", age, "years old")

I am 28 years old


In [ ]:
a, b, c = 10, 5.5, "AI"
print(a,b,c)

10 5.5 AI


In [ ]:
a = 3
print(id(a))

11277992


In [ ]:
a = 5
print(a,"is of type", type(a))

5 is of type <class 'int'>


In [ ]:
a = 5.4
print(a,"is of type", type(a))

5.4 is of type <class 'float'>


In [ ]:
a = 5 + 2j
print(a,"is of type", type(a))

(5+2j) is of type <class 'complex'>


In [ ]:
single_quoted = 'hai ravi'
print(type(single_quoted))

<class 'str'>


In [ ]:
double_quoted = "hai ravi"
print(type(double_quoted))

<class 'str'>


In [ ]:
multi_string = '''hai ravi'''
print(type(multi_string))

<class 'str'>


Sting Indexing

In [ ]:
#string indexing
my_string = "Raviteja"
print(my_string[0])
print(my_string[1])
print(my_string[2])
print(my_string[3])
print(my_string[4])
print(my_string[5])

R
a
v
i
t
e


In [ ]:
#string slicing
my_string = "python"
print(my_string[1:4])

yth


In [ ]:
print(my_string[2:5])

tho


In [ ]:
print(my_string[2:-1])

tho


In [ ]:
#string Concatenation
str1 = "hello"
str2 = "world"
concatenated_str = str1 + " "+ str2
print(concatenated_str)

hello world


In [ ]:
my_string = "  Python "
print(len(my_string))

9


In [ ]:
print(my_string.lower())

  python 


In [ ]:
print(my_string.upper())

  PYTHON 


In [ ]:
print(my_string.replace('e', "i"))

  Python 


In [ ]:
my_string = "python"
print(len(my_string))

6


LISTS

In [ ]:
my_list = [1,2,3,4,5]
print(my_list)

[1, 2, 3, 4, 5]


In [ ]:
my_list2 = ['a', 10, 20.4, "Raviteja"]
print(my_list2)

['a', 10, 20.4, 'Raviteja']


In [ ]:
print(my_list[0])

a


In [ ]:
print(my_list[2])

3


In [ ]:
my_list[0] = 8
print(my_list)

[8, 2, 3, 4, 5]


In [ ]:
my_list[2] = 'Ravi'
print(my_list)

[8, 2, 'Ravi', 4, 5]


In [ ]:
#list reverse
my_list = [1,2,3,4,5]
my_list.reverse()
print(my_list)

[5, 4, 3, 2, 1]


In [ ]:
print(my_list)

[1, 2, 3, 4, 5]


In [ ]:
#Modifying lists
my_list[1] = 10
my_list.append(6)
my_list.remove(3)
print(my_list)

[1, 10, 4, 5, 6]


In [ ]:
#List concatenation
list1 = [1,2,3]
list2 = [4,5,6]
combined_list = list1 + list2
print(combined_list)

[1, 2, 3, 4, 5, 6]


In [ ]:
#list repetiton
repeated_list = [0] * 10
print(repeated_list)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
#len of list
print(my_list)
length = len(my_list)
print(length)

[1, 10, 4, 5, 6]
5


In [ ]:
#Nested list
nested_list = [[1,2,3],[4,5,6],[7,8,9]]
print(nested_list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
nested_list [2] [2]

9

In [ ]:
print(my_list)

[1, 10, 4, 5, 6]


TUPLES


In [ ]:
my_tuple = (1,2,3,4,5)
my_tuple

(1, 2, 3, 4, 5)

In [ ]:
tuple2 = (1,2.5,"Balaji", 2+3j, [1,5.78,"data"])
tuple2

(1, 2.5, 'Balaji', (2+3j), [1, 5.78, 'data'])

In [ ]:
print(tuple2[0])
print(tuple2[2])

1
Balaji


In [ ]:
type(tuple2[1:4])

tuple

In [ ]:
my_tuple[0] = 10
my_tuple

TypeError: 'tuple' object does not support item assignment

In [ ]:
my_list = [1,2,3,4,5,6,7,8,9]
my_list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
my_list[0] = 10
my_list

[10, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
my_tuple = ('apple', 'banana', 'cherry', 'date', 'elderberry')
subset_tuple = my_tuple[1:4]
print(subset_tuple)

('banana', 'cherry', 'date')


In [ ]:
my_tuple = ('a', 'b', 'c', 'd', 'e','f')
print(my_tuple[-2])

e


In [ ]:
print(my_tuple[3])

d


In [ ]:
my_tuple = [1,2,3,4,5,6,7,8,9]
my_tuple

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
my_tuple = [1,2,3,4,5,6,7,8,9,2,2,2,2,2]
my_tuple.count(2)

6

SETS


In [ ]:
my_set = {1,2,3,4,5}
my_set

{1, 2, 3, 4, 5}

In [ ]:
type(my_set)

set

In [ ]:
another_set = set([3,4,5,6,7,8,9,0,1])
another_set

{0, 1, 3, 4, 5, 6, 7, 8, 9}

In [ ]:
another_set[0]

TypeError: 'set' object is not subscriptable

In [ ]:
my_set

{1, 2, 3, 4, 5}

In [ ]:
my_set.add(6)
my_set

{1, 2, 3, 4, 5, 6}

In [ ]:
my_set.update({8,9,10})
my_set

{1, 2, 3, 4, 5, 6, 8, 9, 10}

In [ ]:
my_set.remove(6)
my_set

{1, 2, 3, 4, 5, 8, 9, 10}

In [ ]:
popped_element = my_set.pop()
popped_element

1

In [ ]:
set_a = {1,2,3,4,5}
set_b = {4,5,6,7,8}

In [ ]:
set_a.union(set_b)

{1, 2, 3, 4, 5, 6, 7, 8}

In [ ]:
set_a.intersection(set_b)

{4, 5}

In [ ]:
set_a.difference(set_b)

{1, 2, 3}

In [ ]:
set_a = {1,2,3,4,5}
set_b = {4,5,6,7,8}
set_a.difference_update(set_b)
print("After difference_update, set_a:", set_a)

After difference_update, set_a: {1, 2, 3}


In [ ]:
#Resetting sets for the next example
set_a = {1,2,3,4,5}
set_b = {4,5,6,7,8}

#Using -= operator (difference)
set_c = set_a -set_b
print("After difference using -= operator, set_a:",set_c)

After difference using -= operator, set_a: {1, 2, 3}


In [ ]:
my_set.clear()

In [ ]:
my_set()
my_set

TypeError: 'set' object is not callable

In [ ]:
set_copy = my_set.copy()

Dictonaries


In [ ]:
my_dict = {"name": "John", "age": 30, "city": "New York", "colors": ["red", "white", "blue"], 1:10}
# Values can be any datatype
my_dict

{'name': 'John',
 'age': 30,
 'city': 'New York',
 'colors': ['red', 'white', 'blue'],
 1: 10}

In [ ]:
dict1 = {2:3}
print(type(dict1))

<class 'dict'>


In [ ]:
my_dict = {"name": "john","age":30, "city":"New York","colors": ["red", "white", "blue"], 1:10}
my_dict

{'name': 'john',
 'age': 30,
 'city': 'New York',
 'colors': ['red', 'white', 'blue'],
 1: 10}

In [ ]:
my_dict = {"name": "john","age":30, ["city","balu"]:"colors": ["red", "white", "blue"], 1:10}
my_dict

SyntaxError: invalid syntax (476308534.py, line 1)

In [ ]:
len(my_dict)

5

In [ ]:
#Nested Dict
my_dict1 = {1:'balaji', 2: 'is', 3:{'A':'data scientist','B':'hello','c':'world'}}
my_dict1

{1: 'balaji', 2: 'is', 3: {'A': 'data scientist', 'B': 'hello', 'c': 'world'}}

In [ ]:
# The dict() Constructor
thisdict = dict(name = "John", age = 36, country = "Norway")
print(thisdict)

{'name': 'John', 'age': 36, 'country': 'Norway'}


In [ ]:
my_dict.get('hello')
my_dict.get

<function dict.get(key, default=None, /)>

Type Casting

In [ ]:
x = 3
y = 2.5
print(x, type(x))
print(y, type(y))
print(x+y,type(x+y))

3 <class 'int'>
2.5 <class 'float'>
5.5 <class 'float'>


OPERATORS

Arithmetic Operators
1. Addition(+)
2. Subtraction (-)
3. Multiplication (*)
4. Division (/)
5. Modulus - remainder of the division(%)
6. Exponentiation (**)
7. Floor Division- division rounded down to the nearest whole number(//)

In [ ]:
a = 10
b = 3
print(a+ b)
print(a- b)
print(a* b)
print(a/ b)
print(a% b)
print(a** b)
print(a// b)

13
7
30
3.3333333333333335
1
1000
3


Comparison Operators
1. == (Equal to)
2. != (Not Equal to)
3. <(Less than)
4. '>'(Greater than)
5. <= (Less than or equal to)
6. '>=' (Greater than or equal to)


In [ ]:
x = 10
y = 5
print(x == y)
print(x != y)
print(x < y)
print(x > y)
print(x <= y)
print(x >= y)


False
True
False
True
False
True


Logical Operators:
1. and (Logical AND)
2. or (Logical OR)
3. not (Logical Not)


In [ ]:
a = True
b = False
print(a and b)
print(a or b)
print(not a)

False
True
False


In [ ]:
a = 5
b = 3

print(a<10 or b>10)

Assignment Operators


Bitwise operators:

In [ ]:
a = 5
bin(a)

'0b101'

In [ ]:
int('0b000000101', base = 2)

5

In [ ]:
a = 5
b = 3
result = a & b
result

1

In [ ]:
a = 5
b = 3
result = a | b
result

7

In [ ]:
a = 5
b = 3
result = a ^ b
result

6

In [ ]:
a = 5
print(bin(a))


result = ~a
result

0b101


-6

In [ ]:
a = 5
result = a << 1
result

10

In [ ]:
a = 5
result = a >> 1
result

2

IF ELSE Conditions:
The if statement is uesd to execute a block of code only if a certain condition is true .
if condition:
code to be execute if condtions is true

In [ ]:
new_mobile_price = 40000
budget = 25000
if budget > new_mobile_price:
    print('I am getting an mobile phone')

In [ ]:
new_mobile_price = 40000
budget = 25000
if budget < new_mobile_price:
    print('I am not getting an mobile phone')

I am not getting an mobile phone


In [ ]:
#Else
#if condition:
    #code to be executed if the condition is true
#else:


IndentationError: expected an indented block after 'if' statement on line 2 (4013287657.py, line 4)

In [ ]:
new_mobile_price = 25000
budget = 40000

In [ ]:
if budget<new_mobile_price :
    print("I am not getting smart phone")
else:
    print("I am getting an smart phone")


I am getting an smart phone


In [ ]:
percentage = 75
if percentage >= 90:
    print("Grade: A")
if percentage >= 80:
    print("Grade: B")
if percentage >= 70:
    print("Grade: C")
if percentage >= 60:
    print("Grade: D")
if percentage >= 50:
    print("Grade: E")


Grade: C
Grade: D
Grade: E


In [ ]:
if percentage > 90 and percentage <99:
    print("Grade : A")
if percentage >= 80 and percentage <89:
    print("Grade : B")
if percentage >= 70 and percentage <79:
    print("Grade : C")
if percentage >= 60 and percentage <69:
    print("Grade : D")
if percentage >= 50 and percentage <59:
    print("Grade : E")

Grade : C


3. elif Statement:
The elif statement (short for "else if") is used to check multiple cinditions in sequence.
1. it is used after an if statement and before an optional else statement

In [ ]:
#syntax

if condition1:
    #code to be executed if condition1 is true
elif condition2:
     #code to be executed if condition2 is true
elif condition3:
     #code to be executed if condition1 and condition2 is true
else:
    #code to be executed if conditions are true

IndentationError: expected an indented block after 'if' statement on line 3 (273282889.py, line 5)

In [ ]:
percentage = 75
if percentage >=90:
    print("Grade:A")
elif percentage >=80:
    print("Grade:B")
elif percentage >=70:
    print("Grade:C")
elif percentage >=60:
    print("Grade:D")
else:
    print("Grade:F")

print("End")

Grade:C
End


NESTED

In [ ]:
#Example: Nested IF-Else and Elif
num = 0
if num >0:
    print("Positive number")
    if num % 2 == 0:
        print("Even number")
    else:
        print("odd number")

elif num < 0:
    print("Negative number")

else:
        print("zero")

zero


While loop

In [ ]:
#Example: print numbers from  1 to 5 using a while loop
counter = 1
while counter <=5:
    print("raviteja is a business man ", counter)
    counter += 1

raviteja is a business man  1
raviteja is a business man  2
raviteja is a business man  3
raviteja is a business man  4
raviteja is a business man  5


In [ ]:
counter = 5
while counter >=1:
    print("raviteja is a business man ", counter)
    counter -= 1

raviteja is a business man  5
raviteja is a business man  4
raviteja is a business man  3
raviteja is a business man  2
raviteja is a business man  1


In [ ]:
# Nested While loop
counter = 1

counter_2 = 1
while counter <=5 :
    print("Raviteja is a Hardworking man",counter)

    while counter_2 <=5:
        print("Raviteja is a great student", counter_2)
        counter_2 +=1
    counter += 1

Raviteja is a Hardworking man 1
Raviteja is a great student 1
Raviteja is a great student 2
Raviteja is a great student 3
Raviteja is a great student 4
Raviteja is a great student 5
Raviteja is a Hardworking man 2
Raviteja is a Hardworking man 3
Raviteja is a Hardworking man 4
Raviteja is a Hardworking man 5


In [ ]:
#Getting Squares of Numbers.

numbers = [2,3,4 ,5,6,7,8]
sum_of_squares = 0
index = 0
while index < len(numbers):
    sum_of_squares = sum_of_squares + numbers[index] ** 2
    index += 1
print("sum of squares is: {}".format(sum_of_squares))


sum of squares is: 203


While loop with else

In [ ]:
counter = 1
while counter <= 5:
    print("Raviteja is great", counter)
    counter += 1
else:
        print("counter reached")

Raviteja is great 1
Raviteja is great 2
Raviteja is great 3
Raviteja is great 4
Raviteja is great 5
counter reached


In [ ]:
counter = 5
while counter >= 1 :
    print("Raviteja is great", counter)
    counter -= 1
else:
        print("counter reached")

Raviteja is great 5
Raviteja is great 4
Raviteja is great 3
Raviteja is great 2
Raviteja is great 1
counter reached


For Loop
1. for:keyword indicating the start of the loop.
2. variable: A variable that takes on the value of each item in the iterable during each iteration.
3. in:keyword used to specify the iterable.
4. iterable: The sequence or iterable object being lopped over.
5. :Colon, indicating the start of the indented code block that will be executed for each iteration.

In [ ]:
fruits = ["apple","grapes","Mango"]
for i in fruits:
    print(i)

apple
grapes
Mango


Range Function :
We can generate a sequence of numbers using range() function. range (10) will generate numbers from 0 to 9(10 numbers)
we can also define the (start, stop and step size). step size defaults to 1 if not provided.
This function does not store all the values in memory, it would be inefficient. so it remembers the start,stop, step size and generates the next number on the go .

In [ ]:
for i in range(5):
    print(i)

0
1
2
3
4


In [ ]:
#print range of numbers from 1 to 20 with step size of 2
for i in range(0,20,5):
    print(i)

0
5
10
15


In [ ]:
fruits = ["apple","grapes","mango"]
for i in fruits:
    print(i)

apple
grapes
mango


In [ ]:
len(fruits)

3

In [ ]:
for index in range(len(fruits)):

    print(fruits[index])

apple
grapes
mango


In [ ]:
# Enumerate Function

fruits = ["apple","grapes","mango"]
for index, value in enumerate(fruits):
    print(f"index:{index}, value:{value}")

index:0, value:apple
index:1, value:grapes
index:2, value:mango


In [ ]:
# for loop withh strings

greetings = 'hello'
for letter in greetings:
    print(letter)

h
e
l
l
o


In [ ]:
#Else in for loop
#syntax
#for variable in iterable:
    # code to be executed for each iteration
#else:
    # code to be executed when the loop has iterated through all items

In [ ]:
fruits = ["apple","grape","mango"]

for fruit in fruits:
    print(fruit)
else:
    print("no more fruits to iterate")

apple
grape
mango
no more fruits to iterate


In [ ]:
#elif in a for loop

#syntax
#Indendation matters

#for variable in iterable:
   # if condition:
        #code to be executed if the condition is true
        #
    #elif another_condition:
        # code to be executed if the another_condition is true
        #
    #else:
        # code to be executed if no conditions are true
        #

In [ ]:
numbers = [1,2,3,4,5]

for num in numbers:
    if num % 2 == 0:
        print(f"{num} is even")
    else:
        print(f"{num} is odd")

1 is odd
2 is even
3 is odd
4 is even
5 is odd


In [ ]:
# Example code with a more complex for loop and nested if-else statements

# Assume a list of dictionaries representing students and their grades
students = [
    {"name": "Alice", "percentage": 85},
    {"name": "Bob", "percentage": 92},
    {"name": "Charlie", "percentage": 78},
    {"name": "David", "percentage": 95},
    {"name": "Eva", "percentage": 88}
]

# Loop through each student dictionary in the list
for student in students:
    # Extract student information
    name = student["name"]
    percentage = student["percentage"]

    # Determine the grade category
    if percentage >= 90:
        category = "Excellent"
    elif 80 <= percentage < 90:
        category = "Good"
    elif 70 <= percentage < 80:
        category = "Average"
    else:
        category = "Below Average"

    # Print the student's information along with their grade category
    print(f"{name}'s percentage is {percentage}. Category: {category}")

Alice's percentage is 85. Category: Good
Bob's percentage is 92. Category: Excellent
Charlie's percentage is 78. Category: Average
David's percentage is 95. Category: Excellent
Eva's percentage is 88. Category: Good


In [ ]:
# Displaying prime numbers between 2 given numbers

start_range = 20
end_range = 50

print("Prime numbers between {0} and {1} are:".format(start_range, end_range))
for num in range(start_range, end_range +1):
    if num > 1:
        is_prime = True
        for divisor in range(2, num):
            if num % divisor == 0:
                is_prime = False
                break
        if is_prime:
                print(num)

Prime numbers between 20 and 50 are:
23
29
31
37
41
43
47


In [ ]:
start_range = 20
end_range = 50

print("Prime numbers between {0} and {1} are:".format(start_range, end_range))

for num in range(start_range, end_range + 1):  # Default step size is 1
    if num > 1:
        is_prime = True
        for divisor in range(2, num):
            if num % divisor == 0:
                is_prime = False
                break
        if is_prime:
            print(num)

Prime numbers between 20 and 50 are:
23
29
31
37
41
43
47


Break

1. break and continue statements can alter the flow of a normal loop.
2. The break statement is used to exit a loop prematurely. when a break statement is encountered within a loop, the loop is immediately terminated, and the program continues with the next statement after the loop.

In [ ]:
#syntax
#for variable in iterable:
    #code to be executed for each iteration
    #if condition:
     #   break #Exit the loop if the condition is true

    #else condition:


In [ ]:
numbers = [1,2,3,4,5]

for num in numbers:
    if num == 3:
        print("Found 3!")
        break
    print(num)

1
2
Found 3!


In [ ]:
numbers = [1,2,3,4]

for num in numbers:         #iterating over list
    if num == 5:
        print("Found 4!")
        break
    print(num)
else:
    print("in the else block ")
print("outside of the loop")

1
2
3
4
in the else block 
outside of the loop


**Continue Statement **

The continue staetment is used to skip the rest of the code inside a loop for the current iteration and move on to the next iteration. here's an example:


In [ ]:
#Example using continue statement

numbers = [1,2,3,4,5,6]

for num in numbers:
    if num % 2 == 0:
        print(f"skipping even number: {num}")
        continue
    print(num)

1
skipping even number: 2
3
skipping even number: 4
5
skipping even number: 6


In [ ]:
#pass statement


#example using pass statement

numbers = [1,2,3,4,5,6]
for num in numbers:
    if num == 4:
        print("found 4. fuck you ")
        pass
    print(num)

1
2
3
found 4. fuck you 
4
5
6


Functions in Python are a fundamental building block of the language. They allow you to create reusable code segments that can perform a specific task, which can then be utilized to build more complex programs. Let's explore functions in detail:

Why Functions?
1. Modularity: Functions help to break down complex processes into smaller, manageable, and modular pieces.
2. Reusability: Once a function is defined, it can be used multiple times throughout a program without needing to rewrite code.
3. Organization: Functions help to organize code into logical groups.
4. Maintenance: If a change is required, you only need to update the code in one place, making maintenance easier.

In [ ]:
#Syntax
def function_name(parameters):
    #Do something with the parameters

    return result #return is optional

1. keyword "def" marks the start of function header

2. Parameters (arguments) through which we pass values to a function. These are optional

3. A colon(:) to mark the end of funciton header

4. Doc string describe what the function does. This is optional

5. "return" statement to return a value from the function. This is optional

In [ ]:
print('hello world')

hello world


In [ ]:
print("hello world")
print("Ravi is great")

hello world
Ravi is great


In [ ]:
def printworld():
    print("hello world")
    print("Ravi is great")


In [ ]:
printworld()

hello world
Ravi is great


In [ ]:
a = 10
b = 20
print(a+b)

30


In [ ]:
print(a+b)

30


In [ ]:
print(30+20)

50


In [ ]:
print(a+b)

30


Parameters vs. Arguments
1. Parameters: These are the variables listed inside the parentheses in the function definition.
2. Arguments: These are the actual values passed to the function when it is called.

In [ ]:
def add_numbers(a,b):

     result = a + b
     print(result)


#use the function
add_numbers(10,5)

15


In [ ]:
add_numbers(20,40)

60


Return in functions

In [ ]:
#using return
def add_numbers(a, b):
    result =a+b
    return result

    #use this function
sum_result = add_numbers(10,5)
print(sum_result)

15


In [ ]:
add_numbers(10, 5)

15

In [ ]:
#use the function
sum_result = add_numbers(10,3)
print(sum_result)

13


In [ ]:
def get_sum(list):
    """This function returns the sum of all the elements in a list"""
    #intialize sum
    sum = 0

    #iterating over the list
    for num in list:
        sum += num
    return sum

In [ ]:
s = get_sum([1,2,3,4])
print(s)

10


In [ ]:
s = get_sum([1,10,30,47])
print(s)

88


Returning multiple Values

In [ ]:
def get_min_max(numbers):
    return min(numbers),max(numbers)

In [ ]:
a = get_min_max([1,2,3,4,5])
print(a)

(1, 5)


In [ ]:
a[0]

1

In [ ]:
minimum, maximum =get_min_max([1,2,3,4,5])
print(minimum,maximum)

1 5


Scope of Variables:
1. Variables defined within a function are scoped to that function and are not accessible outside of it. This is known as local scope:

In [ ]:
def multiply(x, y):
    result = x * y
    print(result)
    return result

In [ ]:
print(multiply(2,3))

6
6


In [ ]:
print(result)

NameError: name 'result' is not defined

In [ ]:
#global_var and local_var

global_var = "This is global variable"
def test_life_time():
    """This function test the life time of a variables"""
    local_var = "This is local variable"
    print(local_var)

    print(global_var)

In [ ]:
test_life_time()

This is local variable
This is global variable


In [ ]:
print(global_var)

This is global variable


In [ ]:
print(local_var)

NameError: name 'local_var' is not defined

DOCSTRINGS

In [ ]:
def add (a,b):
    """Return the sum of a and b """
    return a + b

In [ ]:
print(add._doc_)

AttributeError: 'function' object has no attribute '_doc_'

In [ ]:
print(add.__doc__)

Return the sum of a and b 


In [ ]:
print(add.__doc__)

Return the sum of a and b 


In [ ]:
a = {'city ': 'bangalore', 'age':'30'}
a['bangalore']

KeyError: 'bangalore'

Return Key from Value in dictionaries

In [ ]:
def get_key_from_value(d, val):
    keys = [k for k,v in d.items() if v == val]
    print(keys)
    if keys:
        return keys[0]
    return None

In [ ]:
a = {'city ': 'bangalore', 'age':'30'}
key = get_key_from_value(a, 'bangalore')
print(key)

['city ']
city 


Real Life Task and how to handle.
Let's tackle a simple real-life task: organizing a small personal library. We'll write functions to add a book, remove a book, and list all books. This will demonstrate the use of functions to manage a collection.

-- Task Description We have books in our personal library, each with a title and an author. We want to be able to:

1. Add a new book to the library.
2. Remove a book from the library by title.
3. List all books currently in th

In [ ]:
#our personal libary represented as a list of dictionaries
libary=[]

#Function to add a book to the libary
def add_book(title, author):
    libary.append({'titl': title,'author': author})
    print(f"'{title}' by {author} has been added to the libary. ")

In [ ]:
libary

[]

In [ ]:
#Adding books
add_book("The lion king ", "F. scott")

'The lion king ' by F. scott has been added to the libary. 


In [ ]:
# Our personal library represented as a list of dictionaries
library = []

# Function to add a book to the library
def add_book(title, author):
    library.append({'title': title, 'author': author})
    print(f"'{title}' by {author} has been added to the library.")

# Function to remove a book from the library by title
def remove_book(title):
    global library
    library = [book for book in library if book['title'] != title]
    print(f"'{title}' has been removed from the library.")

# Function to list all books in the library
def list_books():
    if library:
        print("Books in the library:")
        for book in library:
            print(f"{book['title']} by {book['author']}")
    else:
        print("The library is currently empty.")

Names between the parentheses are called parameters, and the actual values you provide when you call the function are called arguments. Python has several types of arguments that a function can accept

Positional Arguments

In [ ]:
#These are arguments that need to be included in the proper position or order.


def add(a,b):
    print("value of a is :",a)
    print("value of b is :",b)
    return a + b

print(add(2,3))

value of a is : 2
value of b is : 3
5


In [ ]:
print(add(3,2))

value of a is : 3
value of b is : 2
5


Keyword Arguments:
1. These are arguments passed to a function by explicitly specifying the name of the parameter and the corresponding value. They can be put in any order because Python interprets the names.

In [ ]:
def person_info(name, age):
    return f"{name} is {age} years old."

print (person_info(26, "Ravi"))

26 is Ravi years old.


In [ ]:
print(person_info("Ravi", 26))

Ravi is 26 years old.


In [ ]:
print(person_info(name = "Ravi",age = 26))

Ravi is 26 years old.


Default Arguments
These are arguments that take a default value if no argument value is passed during the function call.

In [ ]:
def person_info(name, age):
    return f"{name} is {age} years old."

print(person_info( "Ravi", 26))

Ravi is 26 years old.


In [ ]:
print(person_info(name = "Ravi", age = 26))

Ravi is 26 years old.


In [ ]:
def person_info(name, age = 27):
    return f"{name} is {age} years old."
print(person_info(name = "bhanu"))

bhanu is 27 years old.


In [ ]:
print(person_info("balu"))

balu is 27 years old.


In [ ]:
print(person_info(name = "balu", age = 27))

balu is 27 years old.


Arbitrary Arguments

1. Sometimes, you might not know how many arguments will be passed into your function. python allows you to handle this kind of situation through arbitrary arguments.

2. Arbitrary Positional Arguments (*args): They are often used when you want to pass a variable number of non-keyword arguments to a function.

In [ ]:
def add_all_numbers(*ravi):
    return sum (ravi)
    print(ravi)
print(add_all_numbers(1,2,3,4))

10


In [ ]:
def print_all(*args):
    for arg in args:
        print (arg)

print_all('apple', 'banana', 'Mango')

apple
banana
Mango


In [ ]:
#calling function with five arguments
print_all('dog', 'cat','rat','sat','fri')

dog
cat
rat
sat
fri


In [ ]:
def print_all(*Ravi):
    print("parameter Ravi contains- ", Ravi)
    for arg in Ravi:
        print(arg)

print_all('apple','banana','Mango')

parameter Ravi contains-  ('apple', 'banana', 'Mango')
apple
banana
Mango


1. Arbitrary Keyword Arguments (**kwargs): They are used when you want to pass a variable number of keyword arguments to a function.
2. Arbitrary keyword arguments allow you to handle named arguments that you have not predefined in your function

In [ ]:
def person_info(**kwargs):
    print(kwargs)
    info = ""
    for key, value in kwargs.items():
        info += f"{key} is {value}."
    return info

In [ ]:
print(person_info(name= "John", age =28, city= "Austin"))

{'name': 'John', 'age': 28, 'city': 'Austin'}
name is John.age is 28.city is Austin.


In [ ]:
def introduce_yourself(**kwargs):
    for key, value in kwargs.items():
        print(f"{key} is {value}")

introduce_yourself(MYName="John", age= 30, city="Dallas", profession = "CA")

MYName is John
age is 30
city is Dallas
profession is CA


In [ ]:
#Calling function with additional named arguments
introduce_yourself(Name = "Gahana", age = 25, city= "indianapolis", sex ="F")

Name is Gahana
age is 25
city is indianapolis
sex is F


In [ ]:
#Examples Mixes Both

def setup_profile(name,  email, *args, **kwargs):
    print(f"Name: {name}")

    print(f"Email: {email}")
    for arg in args:
        print(arg)
        for key, value in kwargs.items():
              print(f"{key}: {value}")

In [ ]:
setup_profile(
    'Jane Doe', 'jane@example.com',
    'Loves Python', 'Writes Code',
    Age=28, Occupation='Developer', Hobby='Cycling'
)

Name: Jane Doe
Email: jane@example.com
Loves Python
Age: 28
Occupation: Developer
Hobby: Cycling
Writes Code
Age: 28
Occupation: Developer
Hobby: Cycling


In [ ]:
setup_profile('Jane Doe', 'jane@example.com','Loves Python', 'Writes Code',
    Age=28, Occupation='Developer', Hobby='Cycling')

Name: Jane Doe
Email: jane@example.com
Loves Python
Age: 28
Occupation: Developer
Hobby: Cycling
Writes Code
Age: 28
Occupation: Developer
Hobby: Cycling


Unpacking Arguments

In [ ]:
def person_info(name, age, city):
    return f"{name} is {age} years old and lives in {city}. "

In [ ]:
person_info("Ravi", 27, "Houston")

'Ravi is 27 years old and lives in Houston. '

In [ ]:
#Unpacking a dictionary in to keywords arguments
details_dict = {'name': 'Ali', 'age' : 38, 'city' :'Houston'}
print(person_info(**details_dict))

Ali is 38 years old and lives in Houston. 


Real Life example
Logging is extensively used in many applications and advantages are -

1. Error Tracking
2. Performance Monitoring
3. Status check etc....

In [ ]:
import datetime


def log_message(*messages, **additional_data):

    """Logs a message with optional additional data.


       Args:
       *messages: Aribitay number of messages to log.
       **additional_data: Arbitrary number of keyword arguments representing additional data to log.
       """

    #Current timestamp
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    #joining all messages in to a single string
    full_message = '| '.join(messages)
    #Creating the base log entery
    log_entry = f"{timestamp} - Message : {full_message}"

    #Adding any additional data to the log entry
    for key, value in additional_data.items():
        log_entry += f" , {key.upper()}: {value}"

# For demonstration, we'll just print the log. In a real application, you might write it to a file or a database.
    print(log_entry)

# Example usage
log_message("Application started", "No errors", urgency="low", user_id="12345")
log_message("Unexpected error occurred", error_code=500, severity="high")


2026-09-12 01:56:31 - Message : Application started| No errors , URGENCY: low , USER_ID: 12345
2026-09-12 01:56:31 - Message : Unexpected error occurred , ERROR_CODE: 500 , SEVERITY: high


In [ ]:
import datetime

def log_message(*messages, **additional_data):
    """
    Logs a message with optional additional data.

    Args:
    *messages: Arbitrary number of messages to log.
    **additional_data: Arbitrary number of keyword arguments representing additional data to log.
    """
    # Current timestamp
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Joining all messages into a single string
    full_message = ' | '.join(messages)

    # Creating the base log entry
    log_entry = f"{timestamp} - MESSAGE: {full_message}"

    # Adding any additional data to the log entry
    for key, value in additional_data.items():
        log_entry += f", {key.upper()}: {value}"

    # For demonstration, we'll just print the log. In a real application, you might write it to a file or a database.
    print(log_entry)

# Example usage
log_message("Application started", "No errors", urgency="low", user_id="12345")
log_message("Unexpected error occurred", error_code=500, severity="high")

2026-09-12 01:51:59 - MESSAGE: Application started | No errors, URGENCY: low, USER_ID: 12345
2026-09-12 01:51:59 - MESSAGE: Unexpected error occurred, ERROR_CODE: 500, SEVERITY: high


Built in Functions


In [ ]:
#len()

my_list=[1,2,3,4]
print(len(my_list))

4


In [ ]:
#abs()

number = -5
print(abs(number))

5


In [ ]:

number = 20
print(abs(number))

20


In [ ]:
#all()

#return value of all() function
#True: if all elements in an iterable are true
#False: if any element in an iterable is false


lst = [1,2,3,4]
print(all(lst))

True


In [ ]:
lst = [0,1,2,3,4]
print(all(lst))

False


In [ ]:
tuple = (1,-2,0,4)
print(all(tuple))

False


In [ ]:
tuple = (1,-2,6,4)
print(all(tuple))

True


In [ ]:
tuple1 = {}
print(all(tuple1))

True


In [ ]:
lst = [1,2,3,4, "haii", 4.5, {"Name": "Raviteja"}]
print(all(lst))

True


In [ ]:
lst = [False, 1,2,True, False]
print(all(lst))

False


In [ ]:
tuple1 = (1,2,3,4,5,6)
max(tuple1)

6

In [ ]:
tuple1 = (1,2,3,4,5,6)
min(tuple1)

1

divmod()

Takes 2 numbers and returns a pair of numbers as tuple

In [ ]:
divmod(10,2)


(5, 0)

In [ ]:
divmod(10,'2')

TypeError: unsupported operand type(s) for divmod(): 'int' and 'str'

enumerate()
1. Returns tuple of 2 elements.
2. The enumerate () method adds a counter to an iterable and returns it in the form of an enumerating object.
3. Syntax: enumerate(iterable, start=0)
4. Default start = 0

In [ ]:
numbers = [10,20,30, 40]

for index, num in enumerate(numbers):
    print("index {0} has value {1}".format(index,num))

index 0 has value 10
index 1 has value 20
index 2 has value 30
index 3 has value 40


In [ ]:
numbers = [10,20,30,40]

for index, num in enumerate(numbers,23):
    print("index{0} has value {1}".format(index,num))

index23 has value 10
index24 has value 20
index25 has value 30
index26 has value 40


In [ ]:
string = "Raviteja is a great business man and a healthy man"
print(list(enumerate(string)))

[(0, 'R'), (1, 'a'), (2, 'v'), (3, 'i'), (4, 't'), (5, 'e'), (6, 'j'), (7, 'a'), (8, ' '), (9, 'i'), (10, 's'), (11, ' '), (12, 'a'), (13, ' '), (14, 'g'), (15, 'r'), (16, 'e'), (17, 'a'), (18, 't'), (19, ' '), (20, 'b'), (21, 'u'), (22, 's'), (23, 'i'), (24, 'n'), (25, 'e'), (26, 's'), (27, 's'), (28, ' '), (29, 'm'), (30, 'a'), (31, 'n'), (32, ' '), (33, 'a'), (34, 'n'), (35, 'd'), (36, ' '), (37, 'a'), (38, ' '), (39, 'h'), (40, 'e'), (41, 'a'), (42, 'l'), (43, 't'), (44, 'h'), (45, 'y'), (46, ' '), (47, 'm'), (48, 'a'), (49, 'n')]


In [ ]:
for index, num in enumerate(string,0):
    print("index{0} has value {1}". format(index,num))

index0 has value R
index1 has value a
index2 has value v
index3 has value i
index4 has value t
index5 has value e
index6 has value j
index7 has value a
index8 has value  
index9 has value i
index10 has value s
index11 has value  
index12 has value a
index13 has value  
index14 has value g
index15 has value r
index16 has value e
index17 has value a
index18 has value t
index19 has value  
index20 has value b
index21 has value u
index22 has value s
index23 has value i
index24 has value n
index25 has value e
index26 has value s
index27 has value s
index28 has value  
index29 has value m
index30 has value a
index31 has value n
index32 has value  
index33 has value a
index34 has value n
index35 has value d
index36 has value  
index37 has value a
index38 has value  
index39 has value h
index40 has value e
index41 has value a
index42 has value l
index43 has value t
index44 has value h
index45 has value y
index46 has value  
index47 has value m
index48 has value a
index49 has value n


Filter()

1. The filter() method constructs an iterator from elements of an iterable for which a function returns true.
2. syntax: filter(function, iterable)
3. Accepts 2 parameters
4. Filter fucntion returns true or false which is boolean

In [ ]:
def find_positive_number(num):
    """ This function returns the positive number if num is positive"""

    if num > 0:
        return num*2

In [ ]:
number_list = range(-10,10)
print(list(number_list))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
positive_num_lst = list(filter(find_positive_number, number_list))
print(positive_num_lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
final = []
for i in number_list:
    if i>0:
        final.append(i)
print(final)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


map()

1. Map applies a function to all the items in an input_list
2. syntax: map(function_to_apply,list_of)inputs

In [ ]:
numbers = [1,2,3,4]

#normal method of computing num^2 for each element in the list.

squared = []
for num in numbers:
    squared.append(num**2)

print(squared)

[1, 4, 9, 16]


In [ ]:
numbers = [1,2,3,4]

def poweroftwo(num):
    return num**2

    #using map() function.
squared = list(map(poweroftwo, numbers))
print(squared)

[1, 4, 9, 16]


Reduce()

1. reduce() function is for performing some computation on a list and returning the result.
2. it applies a rolling computation to sequential pairs of values in a list.

In [ ]:
#product of element in a list
product = 1
lst = [1,2,3,4]

#traditional program without reduce()

for num in lst:
    product *= num
    print(product)

1
2
6
24


In [ ]:
#In python 2 it used to be inbuilt function.
#In python 3 we have to import it.

from functools import reduce

def multiply(x, y):
    return x*y;

product = reduce(multiply, lst)
print(product)


24


isinstance()
1. syntax: isinstance(object, classinfo)

In [ ]:
lst = [1,2,3,4]
print(isinstance(lst, list))

True


In [ ]:
#try with other data types tuples, set

t = {1,2,3,4}
print(isinstance(t, list))

False


User- Defined Functions

Advantages-

1. modularity
2. code reusability
3. simplifies code
4. Ease of Maintenance
5. Debugging Advantage
6. Parameter Passing
7. Encapsulation
8. Reduction of Errors
9. Enhanced collaboration
10. customization and Extension
11. Performance Optimization

In [ ]:
def greet(name):
    return f"Hello, {name}"

print(greet("Ravi"))

Hello, Ravi


In [ ]:
print(greet("balaji"))

Hello, balaji


In [ ]:
def Thankyou(name):
    return f"Thankyou, {name}"

print(Thankyou("Ravi"))

Thankyou, Ravi


Understanding Recursion:

1. Base Case: Every recursive function needs to have a base case, which is a condition that stops the recrusion from continuing indefinitely. without a base case, the function would keep calling itself forever, leading to stack overflow.

2. Recrusive Case: This is the part of the function that includes the recrusive call. The recrusive case must work towards reaching the base case by altering the input.

In [ ]:
#Sample Base Code

def recursive_function(parameters):
    if base_case_condition(parameters):
        return base_case_value
    else:
        return recursive_function(modified_parameters)

Factorial?

1. Representation is !
2. By default 0! = 1 and 1! = 1


In [ ]:
# Factorial(7) = 7*6*5*4*3*2*1
# Factorial(6) = 6*5*4*3*2*1
# Factorial(5) = 5*4*3*2*1
# Factorial(4) = 4*3*2*1

In [ ]:
# Factorial of n = n * (n-1)!

In [ ]:
def factorial(n):
    #base case: if n is o, return 1
    if n < 0:
        return "ravi is great gentle man"
    elif n == 0:
        return 1
        #Recursive case: n! = n * (n-1)!
    else:
        ravi = 1
        for i in range(1, n+1):
            ravi *= i
        return ravi
            #Example usage:
n = 5
print(f"ravi of {n} is {factorial(n)}")

ravi of 5 is 120


In [ ]:
def factorial(n):
    #base case: if n is o, return 1
    if n == 0:
        return 1
        #Recursive case: n! = n * (n-1)!
    else:
        return n * factorial(n-1)
            #Example usage:
print(factorial(5))

EXAMPLE 2



In [ ]:
#write a recursive function to reverse a string

#Recursive Approach
#Base case: If the string is empty or has only one character, it is its own reverse.
#recursive case: To reverse a string, reverse the substring that excludes the first character, and then append the first character to the end.

In [ ]:
def reverse_string(s):
    #base case : empty string or Single character string
    if len(s) <= 1:
        return s
        #Recursive Case: reverse the substring and append the first character
    else:
        return reverse_string(s[1:] )+ s[0]

        #example usage

print(reverse_string("Bhanu"))

unahB


In [ ]:
print(reverse_string("Python"))

nohtyP


Disadvantages

1. Infinite Recursion: Python has a limit on the depth of recursion to prevent a stack overflow. If your recursive call depth goes beyond this limit, you will encounter a RecursionError.

2. Performance: Recursive functions can be less efficient than their iterative counterparts due to the overhead of function calls and returns. Each function call uses a stack frame, and too many frames can lead to high memory usage.

3. Redundant Calculations: In some recursive algorithms like the naive Fibonacci example, the same calculations are performed multiple times, which is inefficient. This can be mitigated by using techniques like memoization.

Lambda Functions
1. Lambda functions in Python, often referred to as anonymous functions, are small, one-line functions defined without a name using the lambda keyword. These functions can have any number of arguments but can only have one expression. The expression is evaluated and returned during function execution. Lambda functions are particularly useful for short-duration use cases where defining a standard function with a def statement is unnecessarily verbose.

In [ ]:
#syntax

lambda arguments: expression

Characteristics

1. Anonymous: They are not declared in the standard manner by using the def keyword and do not need a name.
2. nline: Lambda functions are typically used where you might want to use a function once (though you can use them multiple times if referenced by a variable).
3. Limited: They are limited to a single expression. This means a lambda function can't have multiple expressions or statements like a normal function.

In [ ]:
double = lambda x : x *2
print(double(9))

18


In [ ]:
add = lambda x, y : x + y
print(add(8,3))

11


In [ ]:
#Example  use with filter()
lst = [1,2,3,4,5]
even_lst = list(filter(lambda x : (x%2 == 0), lst))
print(even_lst)

[2, 4]


In [ ]:
lst = [1,2,3,4,5]
new_lst = list(map(lambda x : x ** 2, lst))
print(new_lst)

[1, 4, 9, 16, 25]


In [ ]:
#Example use with reduce

from functools import reduce

lst = [1,2,3,4,5]
product_lst = reduce(lambda x, y : x*y, lst)
print(product_lst)

120


1. Advantage: Quick and concise way to create small functions that are not complex.
2. Limitation: Restricted to single expressions, so they are not suitable for larger functions with multiple expressions or statements.

WHAT ARE Exceptions?

1. In Python, an exception is an error that disrupts the normal flow of a program.
2. When Python encounters an error, it stops the current process and passes it up the call stack until it is handled.
3. If not handled, the program will crash
4. Exceptions could be caused by logical errors in the code, incorrect user inputs, or external conditions, like a file not being accessible.

In [ ]:
a = 10
print(a)
print("Hello world")
print(a**2)
b = 0
print(a/b)


10
Hello world
100


ZeroDivisionError: division by zero

In [ ]:
print("Hello world")

Hello world


In [ ]:
for i in range(10):
    print("hey there)

SyntaxError: unterminated string literal (detected at line 2) (3592729087.py, line 2)

SYNTAX Errors

1. Syntax Errors, also known as parsing errors, are the most basic type of error. They arise when the Python parser detects an incorrect statement. These errors are caught before the program actually runs. The primary cause of syntax errors is typing mistakes or misunderstanding the syntax of Python.

2. Easy to solve in the testing phase.

3. Found out during compiling

In [ ]:
#ValueError example

number = int(input("Enter a number: "))


Enter a number: ba


ValueError: invalid literal for int() with base 10: 'ba'

In [ ]:
 a = 5
 print(a)
 number = int(input("Enter a Number: "))
 print(number*a)
 print(2*a)

5
Enter a Number: 80
400
10


Exception Errors:
Exceptions are errors detected during execution. They occur, even if a statement or expression is syntactically correct, indicating that something went wrong during execution. Exceptions can be handled using try and except blocks, allowing the program to continue or provide a more informative error message.

Exceptions are further categorized into several types, including:

1. ValueError: Raised when a function receives an argument of the correct type but an inappropriate value.
2. TypeError: Occurs when an operation or function is applied to an object of inappropriate type.
3. IndexError: Raised when trying to access an index out of the range of a sequence (like a list or tuple).
4. KeyError: Occurs when a dictionary key is not found.
5. FileNotFoundError: Raised when a file or directory is requested but doesn't exist.
6. ZeroDivisionError: Happens when dividing by zero.
7. IOError (or OSError in newer Python versions): Related to input/output operations, like when a file can't be opened

In [ ]:
try:
    #code block where exception can occur
except ExceptionType:
    #handle the exception

In [ ]:
#Generic Exception Handling
try:
  # some code
except:
    #Here you can do anything
    print("An error occured.")
    # But handling the error in detail is recommended.

IndentationError: expected an indented block after 'try' statement on line 2 (511079141.py, line 4)

In [ ]:
a = 10/2
print(a)

5.0


In [ ]:
a = 10/0
print("value of a is:", a)

if a == 5:
    print("I got the correct output")
else:
    print("something else")

    print("Atleast I am printing something ")


ZeroDivisionError: division by zero

In [ ]:
try:
    a =  10/0
    print("value of a is :",a)

    if a == 5:
        print("i got the correct answer")
    else:
        print("Something else")
except Exception as e:
         print(e)
        #print("you can't divide by zero")
        #print("I am great business man")
print(2+4)

division by zero
6


Value Error

In [ ]:
try:
    int("abc") #Trying to convert a string that does not contain a number
except Exception as e:
        print("ValueError caught:", e)

ValueError caught: invalid literal for int() with base 10: 'abc'


In [ ]:
try:
    int("abc") #Trying to convert a string that does not contain a number
except ValueError as e:
        print("ValueError caught:", e)

ValueError caught: invalid literal for int() with base 10: 'abc'


Type Error

In [ ]:
try:
    "3" + 3 #Attempting to add a string and an integer
except Exception as e:
        print("TypeError caught:", e)

TypeError caught: can only concatenate str (not "int") to str


In [ ]:
try:
    "3" + 3 #Attempting to add a string and an integer
except ValueError as e:
        print("TypeError caught:", e)

TypeError: can only concatenate str (not "int") to str

In [ ]:
try:
    "3" + 3 #Attempting to add a string and an integer
except TypeError as e:
        print("TypeError caught:", e)

TypeError caught: can only concatenate str (not "int") to str


Index Error

In [ ]:
# Define a simple list with three elements

my_list = [1,4,3]

try:
    #Attempt to access an index that is out of bounds
    print(my_list[4])
except IndexError as e:
    print(e)
    #Handle the IndexError
    print("An IndexError occured: Attempted to access an index that doesn't exist.")

    #continue with the rest of the program
print("Program continues after handling the exception.")

print(2+3)

list index out of range
An IndexError occured: Attempted to access an index that doesn't exist.
Program continues after handling the exception.
5


Key Error

In [ ]:
try:
    my_dict = {"a":1, "b":2}
    print(my_dict["c"])
except KeyError as e:
    print("keyError caught:", e)

keyError caught: 'c'


Multiple Exception Blocks

In [ ]:
try:
    x = int(input("Enter an number: "))
    y = 10/ x
    print(x,y)
except ZeroDivisionError:
    print("Division by zero")
except ValueError:
    print("Invalid input, please enter a numeric value.")

Enter an number: ravi
Invalid input, please enter a numeric value.


In [ ]:
try:
    x = int(input("Enter an number: "))
    y = 10/ x
    print(x,y)
except Exception as e:
    print("Don't enter zero.")
    print(e)

Enter an number: ravi
Don't enter zero.
invalid literal for int() with base 10: 'ravi'


In [ ]:
try:
    # Some code that might raise multiple exceptions
    value = 0
    result = 1 / int(value)   #This might raise a ZeroDivisionError or ValueError
    my_list = [1,2,3]
    print(my_list[5])  # This might raise an IndexError
except ValueError as e:
    print("ValueError caught:", e)
except ZeroDivisionError as e:
    print("ZeroDivisionError caught:",e)
except IndexError as e:
    print("IndexError caught:", e)

ZeroDivisionError caught: division by zero


In [ ]:
try:
    #Write your code to try
except:
    #Execute this if this fails.
finally:
    #Execute this anyway

In [ ]:
# Example Usage

string_list = ["10", "20", "30", "a", "56"] # 'a' cannot be converted

try:
    #Attempt to convert each string in the list to an integer and sum them
    total_sum = sum(int(item) for item in string_list)
    print(total_sum)
except ValueError:
    # Handle the case where conersion fails
    print("List contains non numeric values")
finally:
    #This execute regardless of previous blocks success or failure
    print("Raviteja is an AI engineer")

List contains non numeric values
Raviteja is an AI engineer


Common Mistakes and Tipc

1. Catching too broad an exception: Avoid using a bare except: when possible, as it can make debugging harder by catching unexpected errors.
2. Not specifying exception variable: You can specify a variable after the exception type to access the exception object itself, like except ValueError as e:.
3. Forgetting multiple exceptions: You can catch multiple exception types in a single block using a tuple, like except (ValueError, TypeError):

Reel Life Example

A real-life simple example that often requires the use of try, except, and finally is reading from and writing to a file. This operation is common in many applications, such as logging, data processing, and configuration management. Here's why each part of this error handling structure is useful in this context:

1. try block: To attempt to open and read or write to a file, which might not exist or be accessible (due to permissions or being locked).
2. except block: To catch and handle any errors that occur during file operations, such as FileNotFoundError or PermissionError.
3. finally block: To ensure that the file is closed properly, even if an error occurs, preventing resource leaks.

In [ ]:
def log_whatsapp(whatsapp, file_path):
    try:
        #Attempt to open the file in append mode and write a message
        file = open(file_path, 'a')
        file.write(whatsapp +'\n')
        print("file opened and message added")
    except FileNotFoundError:
        #Handle the case where the file does not exist
        print("The file was not found.")
    finally:
        #This block executes no matter what, ensuring the file is closed
        print("close the file")
        file.close()

log_whatsapp("Hello, world! ravi is here", "/content/log.txt")

file opened and message added
close the file


Opening a File

In [ ]:
open('example.txt')

<_io.TextIOWrapper name='example.txt' mode='r' encoding='utf-8'>

In [ ]:
open('example.txt', 'r')

<_io.TextIOWrapper name='example.txt' mode='r' encoding='utf-8'>

1. In file handling, encoding='UTF-8' specifies the character encoding used to interpret the file content when reading from or writing to a file. UTF-8 is a widely-used coding system that represents every character (from nearly every language in the world) as a unique numeric code. This encoding supports a large variety of characters from many different languages, making it a universal standard in file encoding.

2. When you open a file in Python using open(), you can specify the encoding type with the encoding parameter. If you don't specify an encoding, Python uses the default encoding, which is platform-dependent. For instance, the default encoding could be UTF-8 on Linux or macOS and CP1252 on Windows.

3. Specifying encoding='UTF-8' ensures that you correctly handle files containing Unicode text, which includes most human languages and even emojis, making your applications more international and inclusive.

In [ ]:
open('example.txt', 'r').read()

'1 Hello There!\n2 Welcome to my world.\n3 This is an ai engineering course\n4 Happy learning \n5'

In [ ]:
f = open('example.txt','r')
print(f)

<_io.TextIOWrapper name='example.txt' mode='r' encoding='utf-8'>


In [ ]:
print(f.read())

1 Hello There!
2 Welcome to my world.
3 This is an ai engineering course
4 Happy learning 
5


In [ ]:
print(f.readlines())

[]


In [ ]:
f.seek(0)

0

In [ ]:
print(f.readline())

1 Hello There!



In [ ]:
print(f.readline(10))

2 Welcome 


In [ ]:
file = open('example.txt', 'r')
for line in file:
    print(line, end= '')

1 Hello There!
2 Welcome to my world.
3 This is an ai engineering course
4 Happy learning 
5

In [ ]:
file.close()

In [ ]:
file = open('example.txt', 'r')
file.readline()

'1 Hello There!\n'

Writing :
Now what if you want to write something into y file?

In [ ]:
file = open('example_copytxt', 'w')

In [ ]:
file.write('New Line 1- I am in code\n')
file.close()

In [ ]:
file = open('example_copy.txt', 'w')
file.write('New Line 5- Hello, world\n')
file.write('New Line 2- I am amazing.\n')
file.close()

In [ ]:
file = open('example_new.txt', 'w')
file.close()

Append Mode

In [ ]:
file = open('example_append_new.txt', 'r')
file.close()

FileNotFoundError: [Errno 2] No such file or directory: 'example_append_new.txt'

In [58]:
file = open('example_append.txt','a')
file.close()

In [59]:
file.write('New Line 1- Hello, World\n')
file.close()

ValueError: I/O operation on closed file.

In [60]:
file = open('example.txt', 'a')
file.write('New Line 2- I am amazing.\n')
file.close()

In [61]:
file.close()


1. 'r': Read mode (default). The file is opened and a pointer is placed at the beginning of the file's content.
2. 'w': Write mode. If the file exists, it is overwritten. If the file doesn't exist, it is created.
3. 'a': Append mode. Data is added to the end of the file. The file is created if it doesn't exist.
4. 'r+': Read and write mode. The file pointer is placed at the beginning of the file.
5. 'w+': Write and read mode. Overwrites the file if it exists or creates a new file. The file pointer is at the beginning of the file.
6. 'a+': Append and read mode. Data written to the file is added at the end. The file is created if it doesn't exist.

In [63]:
#The with statement handles opening and closing files automatically
with open('example.txt', 'r') as file:
    content = file.read()
    print(content)

1 Hello There!
2 Welcome to my world.
3 This is an ai engineering course
4 Happy learning 
5New Line 2- I am amazing.



Copy Paste

In [64]:
#open the source file in read mode
with open('example.txt', 'r') as source_file:
    content = source_file.read()

In [65]:
content

'1 Hello There!\n2 Welcome to my world.\n3 This is an ai engineering course\n4 Happy learning \n5New Line 2- I am amazing.\n'

In [66]:
# open the target file in append mode and add the content
with open ('target.txt','w') as target_file:
    target_file.write(content) # Append the content to the target file
print("Content from 'source.txt' has been appended to 'target.txt'.")

Content from 'source.txt' has been appended to 'target.txt'.


Optimising above code


1. Reading in chunks: For very large files, instead of reading the entire file content in to memory at once with read(), you might want to read and append in chunks to avoid memory issues.

2. Line by Line reading and appending: If you prefer to process the file line by line (which is also memoery efficient), you can iterate over the source file object.

In [68]:
#open the source file in read mode

with open ('example.txt', 'r') as source_file:
    #open the target file in append mode
    with open('target2.txt', 'a') as target_file:
        #read from source and append to target line by line
        for line in source_file:
            target_file.write(line)

print("Content from 'source.txt' has been appended to 'target.txt' line by line")


Content from 'source.txt' has been appended to 'target.txt' line by line


Error Handling

In [69]:
try:
    with open('nonexistent.txt', 'r') as file:
        print(file.read())
except FileNotFoundError:
        print('The file does not exist ')

The file does not exist 


Work With Binary Files

In [ ]:
#Instead of "r" use "rb" binary

#with open()

In [ ]:
#r+ Mode

#opens a file for both reading and writing. The file pointer is placed at the beginning of the file. the file must exist, or you'll get an error.


In [12]:
def analyze_message(message):

    message = "text"
    cleaned = message.strip()
    Count = len(cleaned)
    print(Count)

In [5]:
def normalize_agent_name(name):
    # Write your solution below.
    normalize_agent_name = name.strip()
    normalize_agent_name = normalize_agent_name.lower()
    normalize_agent_name = normalize_agent_name.replace(" ","_")
    return normalize_agent_name

print(normalize_agent_name("  Atlas Research Agent  "))

atlas_research_agent


In [17]:
def analyze_message(message):
    stripped = message.strip()
    characters = len(stripped)
print(len('characters'))

10


In [22]:
def analyze_message(message):
    analyze_message = ("Can Atlas search the web?")
    len(analyze_message) = ('analyze_message')
print(len(analyze_message))

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (1288917918.py, line 3)

In [28]:
i = 20
print(i)

20


In [36]:
def analyze_message(message):
    # Step 1 & 2: characters and words (same pattern as your assessment)
    cleaned = message.strip()
    characters = len(cleaned)
    words = len(cleaned.split())

    vowel_count = 0
    for char in cleaned:
        if char.lower() in "aeiou":
            vowel_count += 1

    has_question = "?" in cleaned

    result = {

         "characters": characters,
         "words": words,
         "vowels": vowel_count,
         "has_questionmark": has_question
    }
    return result

print(analyze_message("Can Atlas search the web?"))

{'characters': 25, 'words': 5, 'vowels': 7, 'has_questionmark': True}


In [37]:
data = analyze_message("Can Atlas search the web?")
print("characters:", data["characters"])
print("words:", data["words"])
print("vowels:", data["vowels"])
print("has_question:", data["has_question"])

characters: 25
words: 5
vowels: 7


KeyError: 'has_question'

In [38]:
data = analyze_message("Can Atlas search the web?")
print(*data.items(), sep="\n")

('characters', 25)
('words', 5)
('vowels', 7)
('has_questionmark', True)


In [39]:
data = analyze_message("Can Atlas search the web?")
for key, value in data.items():
    print(f"{key}: {value}")

characters: 25
words: 5
vowels: 7
has_questionmark: True


In [40]:
def analyze_message(message):
    cleaned = message.strip()
    characters = len(cleaned)
    words = len(cleaned.split())

    vowel_count = 0
    for char in cleaned:
        if char.lower() in "aeiou":
            vowel_count += 1

    has_question = "?" in cleaned

    result = {
        "characters": characters,
        "words": words,
        "vowels": vowel_count,
        "has_question": has_question
    }
    return result

data = analyze_message("Can Atlas search the web?")

print("{")
print(f'    "characters": {data["characters"]},')
print(f'    "words": {data["words"]},')
print(f'    "vowels": {data["vowels"]},')
print(f'    "has_question": {data["has_question"]}')
print("}")

{
    "characters": 25,
    "words": 5,
    "vowels": 7,
    "has_question": True
}


In [41]:
permissions = {
    "researcher": ["search", "read"],
    "writer": ["read", "write"],
    "admin": ["search", "read", "write", "delete"]
}


def can_use_tool(role, tool):
    # Write your solution below.
    allowed_tools = permissions.get(role, [])
    return tool in allowed_tools


# Try your function here:
print(can_use_tool("researcher", "search"))
print(can_use_tool("researcher", "read"))
print(can_use_tool("writer", "delete"))
print(can_use_tool("writer", "read"))
print(can_use_tool("admin", "read"))
print(can_use_tool("admin", "write"))
print(can_use_tool("admin", "delete"))
print(can_use_tool("admin", "search"))

True
True
False
True
True
True
True
True


What is NumPy?

1. NumPy (Numerical Python) is an open-source Python library that's used in almost every field of science and engineering.
2. It's the backbone of other Python scientific packages like SciPy, Matplotlib, pandas, etc.
3. The power of NumPy comes from its N-dimensional array object, or ndarray, which is a fast, flexible container for large datasets in Python.

Numpy provides:

1.  extension package to Python for multi-dimensional arrays
2. closer to hardware (efficiency)
3. designed for scientific computation (convenience)
4. Also known as array oriented computing

In [1]:
#Install Numpy
!pip install numpy

Importing Numpy

In [2]:
import numpy as np

Creating Arrays

In [3]:
#Create a 1D array

arr_1d = np.array([1,2,3])
print("1D Array:", arr_1d)

1D Array: [1 2 3]


In [4]:
list = [1,2,3]
list

[1, 2, 3]

In [5]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [6]:
#For loop to sqquare numbers.

L = range(1000)
print(L)
%timeit [i**2 for i in L]

range(0, 1000)
90.9 µs ± 25.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [8]:
#For loop to square numbers using Numpy

a = np.arange(1000)
%timeit a**2


1.5 µs ± 286 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [99]:
#2D Array
# Create a 2D array

arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array:", arr_2d)

2D Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [100]:
#Attributes of Array

print("Shape:", arr_2d.shape)

Shape: (3, 3)


In [16]:
print("Size:", arr_2d.size)

Size: 9


In [17]:
print("Shape:", arr_2d.shape)

Shape: (3, 3)


In [18]:
print("Data type:", arr_2d.dtype)

Data type: int64


In [19]:
print("Number of dimensions:", arr_2d.ndim)

Number of dimensions: 2


In [20]:
len(arr_2d)

3

In [21]:
#create an 1D array

arr_1d = np.array([1,2,3])
len(arr_1d)

3

In [25]:
c = np.array([[[1,2,3],[0,1,3]], [[4,5,6],[7,8,9]]])
c

array([[[1, 2, 3],
        [0, 1, 3]],

       [[4, 5, 6],
        [7, 8, 9]]])

In [26]:
c.ndim

3

In [27]:
c.shape

(2, 2, 3)

In [28]:
len(c)

2

In [29]:
c.size

12

Functions for Creating Arrays

In [30]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
b = np.arange(1,20,5) # Start, End, step
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
c = np.linspace(0,10,5)
c

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [38]:
ones_array = np.ones((3,9))
ones_array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [42]:
zeros_array = np.zeros((3,3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
#create an array with a diag function
diagonal = np.diag([1,2,3]) #construct a diagonal array
diagonal

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [45]:
np.diag(diagonal) #Extract diagonal


array([1, 2, 3])

In [47]:
#create an array with an secific value
full = np.full((2,3), 9)
print("Full of 9s:\n", full)

Full of 9s:
 [[9 9 9]
 [9 9 9]]


In [52]:
#create an array using random
random_array = np.random.rand(4)
random_array

array([0.31533469, 0.01351179, 0.15341908, 0.00551061])

Data Types

In [54]:
a = np.arange(10)
a.dtype

dtype('int64')

In [55]:
#You can explicitly specify which data type you want:
a = np.arange(10, dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [56]:
# The default data type is float for zeros and ones function

a = np.zeros((3,3))
b = np.ones((3,3))

print(a)
print("something else")
print(b)

print("**************")
print("Data Type of a is: ", a.dtype)
print("Data Type of b is: ", b.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
something else
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
**************
Data Type of a is:  float64
Data Type of b is:  float64


In [59]:
b = np.array([True, False, True, False]) #Boolean Datatype
b.dtype

dtype('bool')

In [60]:
s = np.array(['Ram', 'Robert', 'Rahim'])
s.dtype

dtype('<U6')

Each built-in data type has a character code that uniquely identifies it.

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

In [70]:
obj_array = np.array([1, "a", True, np.array([1, 2, 3])], dtype = 'O')
print("Object array:", obj_array)
print(obj_array.dtype)

Object array: [1 'a' True array([1, 2, 3])]
object


In [80]:
obj_array = np.array([1, "a", True, np.array([1,2,3])], dtype = 'O')
print("Object array:", obj_array)
print(obj_array.dtype)

Object array: [1 'a' True array([1, 2, 3])]
object


obj_array is a NumPy array with a data type of 'O', meaning it can hold different types of Python objects. Each element can be accessed just like in any other NumPy array, but operations on the array will be limited by the fact that it contains mixed types, and many of NumPy's optimizations for numerical computations won't apply.

Indexing and Slicing

In [81]:
a = np.arange(0,10,2)
print(a)


[0 2 4 6 8]


In [82]:
print(a[3])

6


In [83]:
# For multidimensional arrays, indexs are tuples of integers:
a = np.diag([1,2,3])
print(a)
print("$$$$$$$$$$$$$")


[[1 0 0]
 [0 2 0]
 [0 0 3]]
$$$$$$$$$$$$$


In [84]:
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [85]:
#assigning value

a[2,1] = 50
a

array([[ 1,  0,  0],
       [ 0,  2,  0],
       [ 0, 50,  3]])

In [88]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [89]:
a[1:10:2]

array([1, 3, 5, 7, 9])

In [90]:
#we can also combine assignment and slicing

a = np.arange(10)
print(a)
a[5:]= 10

print("********** After ******")
print(a)

[0 1 2 3 4 5 6 7 8 9]
********** After ******
[ 0  1  2  3  4 10 10 10 10 10]


In [91]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [92]:
b = np.arange(5)
b[::-1]

array([4, 3, 2, 1, 0])

In [93]:
b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [96]:
#create a 3D array
#shape is (2,3,4) -> 2blocks, 3 Rows, 4 columns

array_3d = np.array([[[0,  1,  2,  3],
                      [ 4,  5,  6,  7],
                      [ 8,  9, 10, 11]],

                     [[12, 13, 14, 15],
                      [16, 17, 18, 19],
                      [20, 21, 22, 23]]])
print("Oriinal 3D Array:\n", array_3d)

Oriinal 3D Array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [97]:
# Let's access the element 18, which is in the second block (index 1),
# second row (index 1) of that block, and third column (index 2) in that row.
element = array_3d[1,1,2]
print("Accessed Element:", element)

Accessed Element: 18


In [98]:
element = array_3d[1,2,2]
print("Accessed Element:", element)

Accessed Element: 22


In [105]:
# Slicing a sub-array
# Let's extract a 2D array from the first block
sub_array_3d = array_3d[0,:,:]
print("sub_array_3d from first block:\n", sub_array_3d)

sub_array_3d from first block:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [108]:
# Slicing a sub-array
# Let's extract a 2D array from the first block
sub_array_2d = array_3d[0,:,:]
print("Extracted 2D array from first block:\n", sub_array_2d)

Extracted 2D array from first block:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [109]:
# Slicing to get specific rows across all blocks
# Here, we get the second row (index 1) from both blocks
rows_across_blocks = array_3d[:, 1, :]
print("Second row across all blocks:\n", rows_across_blocks)

Second row across all blocks:
 [[ 4  5  6  7]
 [16 17 18 19]]


In [110]:
# Slicing to get a column across all blocks and rows
# Let's get the third column (index 2) across all blocks and rows
column_across_blocks = array_3d[:, :, 2]
print("Third column across all blocks and rows:\n", column_across_blocks)


Third column across all blocks and rows:
 [[ 2  6 10]
 [14 18 22]]


Copies and Views
A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use np.may_share_memory() to check if two arrays share the same memory block

In [111]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [113]:
np.shares_memory(a,b)


True

In [114]:
b[0]= 10
b

array([10,  2,  4,  6,  8])

In [115]:
#eventhough we modified b,  it updated 'a' because both shares same memory
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [116]:
a = np.arange(10)

c = a[::2].copy() #force a copy
c

array([0, 2, 4, 6, 8])

In [117]:
np.shares_memory(a,c)


False

In [121]:
c[0] = 10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
array_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Importing Numpy

In [3]:
import numpy as np

Elementwise Numpy Operations

In [4]:
#Basic Operations

# create an array

a = np.array([1,2,3,4])

a+1

array([2, 3, 4, 5])

In [5]:
a ** 2

array([ 1,  4,  9, 16])

In [6]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

Elementwise airthematic operations

In [7]:
print(a)

[1 2 3 4]


In [8]:
b = np.ones(4) + 1
print(b)
print(a-b)

[2. 2. 2. 2.]
[-1.  0.  1.  2.]


In [9]:
print(b)

[2. 2. 2. 2.]


In [10]:
a * b

array([2., 4., 6., 8.])

In [13]:
# Matrix multiplication

c = np.diag([1,2,3,4])
print(c * c)
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


Elementwise comparisions

In [14]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
a == b


array([False,  True, False,  True])

In [15]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
a > b


array([False, False,  True, False])

In [16]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
a  <= b


array([ True,  True, False,  True])

In [18]:
#array-wise comparison

a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
c = np.array([1,2,3,4])
np.array_equal(a,b)

False

In [19]:
np.array_equal(a,c)

True

Logical Operations

In [27]:
a = np.array([1,1,0,0], dtype= bool)
a

array([ True,  True, False, False])

In [28]:
np.logical_not(a)

array([False, False,  True,  True])

In [30]:
b = np.array([1,0,1,0], dtype=bool)
b

array([ True, False,  True, False])

In [31]:
np.logical_or(a,b)

array([ True,  True,  True, False])

In [33]:
a = np.array([1,1,0,0], dtype = bool)
b = np.array([1,0,1,0], dtype= bool)

np.logical_and(a,b)

array([ True, False, False, False])

Transcendental functions:

In [34]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [35]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [39]:
a = np.array([0,90])
np.sin(a)

array([0.        , 0.89399666])

In [40]:
a = np.arange(5)
np.log(a)

/tmp/ipykernel_1507/4169074047.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [41]:
np.exp(a) #evaluates e^x for each element in a given input

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

Shape Mismatch

In [42]:
 a = np.arange(4)
 a + np.array([1,2,0,0])

array([1, 3, 2, 3])

Basic Reductions

In [43]:
#computing sums

x = np.array([1,2,3,4])
np.sum(x)

np.int64(10)

In [44]:
x = np.array([[1,1], [2,2]])
x

array([[1, 1],
       [2, 2]])

In [45]:
x.sum(axis = 0)

array([3, 3])

In [49]:
x.sum(axis = 1)

array([2, 4])

Other reductions

In [51]:
 x = np.array([1,3,2])
 x.min()


np.int64(1)

In [52]:
x.max()

np.int64(3)

In [53]:
x.argmin()

np.int64(0)

In [54]:
x.argmax()

np.int64(1)

Logical Operations

In [55]:
np.all([True, True, False ])


np.False_

In [56]:
np.any([True, False, False])


np.True_

In [58]:
#Note: can be used for array comparisions

a = np.zeros((50, 50))
np.any(a != 0 )

np.False_

In [59]:
b = np.array([3,4])

In [60]:
np.all(a == b)

ValueError: operands could not be broadcast together with shapes (50,50) (2,) 

Statistics

In [61]:
x = np.array([1,2,3,4])
y = np.array([[1,2,3], [5,6,1]])
print(x)
print(y)

[1 2 3 4]
[[1 2 3]
 [5 6 1]]


In [62]:
x.mean()

np.float64(2.5)

In [63]:
x.mean()

np.float64(2.5)

In [64]:
np.median(x)

np.float64(2.5)

In [65]:
x.std()

np.float64(1.118033988749895)

In [71]:
#load data into numpy array object
data = np.loadtxt('populations.txt')

FileNotFoundError: populations.txt not found.

In [70]:
data

NameError: name 'data' is not defined

BROADCASTING
1. Basic operations on numpy arrays (addition, etc.) are elementwise

2. This works on arrays of the same size. Nevertheless, It’s also possible to do operations on arrays of different sizes if NumPy can transform these arrays so that they all have the same size: this conversion is called broadcasting.

3. The image below gives an example of broadcasting:

In [75]:
a = np.tile(np.arange(0,40,10), (3,1))
print(a)

a = a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [76]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [77]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [78]:
a = np.arange(0,40,10)
a.shape

(4,)

In [79]:
a = a[:, np.newaxis]  # adds a new axis -> 2D array
a.shape

(4, 1)

Array Shape Manipulation

In [81]:
a = np.array([[1,2,3], [4,5,6]]) # flattening
a.ravel() # return a contiguous flattened array.


array([1, 2, 3, 4, 5, 6])

In [82]:
a.T #Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

Reshaping : The inverse operation to flattening:

In [83]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [84]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [86]:
b = b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
b[0, 0] = 50
a

array([[50,  2,  3],
       [ 4,  5,  6]])

Note and Beware: reshape may also return a copy:

In [88]:
a = np.zeros((3,2))
b = a.T.reshape(3*2)
b[0] = 100
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Adding a Dimension

1. Indexing with the np.newaxis object allows us to add an axis to an array

2. newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus,

3. 1D array will become 2D array

4. 2D array will become 3D array

5. 3D array will become 4D array and so on

In [89]:
z = np.array([1,2,3])
z

array([1, 2, 3])

In [90]:
z[:, np.newaxis]

array([[1],
       [2],
       [3]])

Dimension Shuffling

In [91]:
a = np.arange(4*3*2). reshape(4,3,2)
a.shape

(4, 3, 2)

In [92]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [93]:
a[0,2,1]

np.int64(5)

In [95]:
#Resizing

a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

however, it must not be referred to somewhere else:

In [98]:
b = a
a.resize((4,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False